# Generated by Django 4.1 on 2022-08-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('preptime', models.IntegerField()),
                ('cookingtime', models.IntegerField()),
                ('category', models.CharField(choices=[('VT', 'Vegetarian'), ('VE', 'Vegan'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='VT', max_length=2)),
                ('method', models.TextField(max_length=1000)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
